### PR TITLE
Update Simplified Chinese Translation of version 1.0.8

### PR DESCRIPTION
**Pull request by Gaoyifei1011**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

仅更新简体中文翻译版本
Only update Simplified Chinese Translation of version

## Other information

想问一下作者，未来能否提供添加OCR图片文字识别和二维码扫描创建功能？
I would like to ask the author, can I provide the function of adding OCR picture text recognition and QR code scanning and creation in the future?

## Quality check

Before creating this PR, have you:

- [x] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [x] Verified that the change work in Release build configuration
- [x] Checked all unit tests pass

### CODE REVIEW

**Comment by Gaoyifei1011** [comment]
由于我在合并您修改的代码中发生了冲突，我已经在我Fork的仓库中添加了您最新更改的代码，最终会出现大量的文件被更新。不知道在合并的时候是否会破坏您的仓库，如果会破坏，请您关闭这个PR，联系我，我重新fork项目，再提交
Since I had a conflict in merging the code you modified, I've added your latest changed code to my Fork repository, and eventually a lot of files are updated. I don't know if it will destroy your repository when merging, if it will be destroyed, please close this PR, contact me, I will re-fork the project, and submit it again

**Comment by Akarinnnnn** [comment]
这样吧，你那边仓库新建一个分支（branch），再用你仓库的Pull Request功能同步这边的更改
一千多个文件里甚至还有旧的代码，太夸张了

**Comment by Gaoyifei1011** [comment]
> 这样吧，你那边仓库新建一个分支（branch），再用你仓库的Pull Request功能同步这边的更改 一千多个文件里甚至还有旧的代码，太夸张了

好的，那我先关了这个PR，当时弄出这么多我也很困惑，所以在这里说明一下，万一污染了作者的代码就很尴尬了

**Comment by Akarinnnnn** [comment]
这个故事告诉我们不要乱用rebase，因为rebase是无视记录复制粘贴的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月13日(星期一) 晚上8:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [veler/DevToys] Update Simplified Chinese Translation of version 1.0.8 (PR #558)





 
Closed #558.
 
&mdash;

**Pull request closed without merging**
