### PR TITLE
Added excluding characters for password generator! #905

### PR DESCRIPTION
**Pull request by notcooler**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] New feature or enhancement
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

The password generator works as normal but doesn't have the functionality to exclude characters
Issue Number: #905 

## What is the current behavior?

The password generator has now a extra input field where the user can specify characters to exclude from the password generator. It's seperated via comma's.

image

## Other information
It isn't finished yet and can someone help me how to add translation functionality, because the ui code part of the input field currently looks like this:
```
            <controls:CustomTextBox
                Header="Exclude Characters"
                IsReadOnly="False"
                Text="{x:Bind ViewModel.ExcludedCharacters, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"/>
```

I don't really understand how the translation stuff works so it would be nice if someone could explain how to do it.

## Quality check

Before creating this PR:

- [x] Did you follow the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [x] Did you build the app and test your changes?
- [x] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
- [x] Did you verify that the change work in Release build configuration
- [x] Did you verify that all unit tests pass
- [x] If necessary and if possible, did you verify your changes on:
   - [x] Windows
   - [ ] macOS (DevToys 2.0)
   - [ ] Linux (DevToys 2.0)

### CODE REVIEW

**Comment by btiteux** [comment]
Hello,
Thank you for the update on this tool.

Concerning the localization of your header value you should look in the following file: [PasswordGenerator.resw](https://github.com/notcooler/DevToys/blob/main/src/dev/impl/DevToys/Strings/en-US/PasswordGenerator.resw)

This will allow you to add a new entry for your header, then you need to update the following section of the [LanguageManager.cs](https://github.com/notcooler/DevToys/blob/66ed5ad90a6e563a65e944436bcd675ec42bdb0c/src/dev/impl/DevToys/LanguageManager.cs#L2534) in this file you need to add the same "Key" name that you use in the "PasswordGenerator.resw" file.

Once all of this is done you can replace the Header value in your view like this (replace "{KeyName}" by the name you choose in the PasswordGenerator.resw file):

``` xaml
    <controls:CustomTextBox
        Header="{x:Bind ViewModel.Strings.{KeyName}}"
        IsReadOnly="False"
        Text="{x:Bind ViewModel.ExcludedCharacters, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"/>

```

I hope it will help you finish the update and feel free to ask if you need more help.

**Comment by veler** [comment]
Hi,
The PR looks good to me in overall. Can you please follow @btiteux instructions to localize the text?

**Comment by notcooler** [comment]
Hey @veler @btiteux,

Thanks for the response and help, I have added translation support and also fixed a small typo that i noticed. I think it's ready to be merged now.

**Review by veler — APPROVED** [review]
It looks all good to me, thank you so much for this contribution! :)

**Pull request merged**
