### PR TITLE
Improving translations using Crowdin

### PR DESCRIPTION
**Pull request by abelrodriguez**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [X] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

- To add a new language, you need to download this project, duplicate language files, make the translation, test it, create a PR, etc.
- When we add new features with new items, we don't know if those items have been translated into other languages.
- You need a Visual Studio license (or even worse, editing a RESW file as plain text)

Issue Number: N/A

## What is the new behavior?

I've created a public project for this: https://crowdin.com/project/devtoys

This tool allows adding, modifying and removing translations using Crowdin.com without installing Visual Studio and without knowledge of C#, and allow to know if there are new items without translation.
image

Additionally, now we have a badge with the percentage of translation.
image

## Other information

Note to @veler and @btiteux: currently, I've configured the project with my fork. If this PR is approved we should configure the project with this repository. For that, Crowdin allows integrations through tokens. Additionally, if you have a continuous integration process, you will be able to configure Crowdin to deploy new translations in that process.

I know that this whole process is delicate. So I'm willing to give up the project (renouncing to appear as owner) for the sake of the product.

To add you as project manager, I need a user or an email. Please provide me with one and I will add you to it so you can see the whole flow.

## Quality check

Before creating this PR, have you:

- [X] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [X] Verified that the change work in Release build configuration
- [X] Checked all unit tests pass

### CODE REVIEW

**Comment by abelrodriguez** [comment]
Related with #415 and #350

**Comment by abelrodriguez** [comment]
Related with #421

**Comment by abelrodriguez** [comment]
Related with #422

**Comment by btiteux** [comment]
Hello,

Thank you for the feature.

I just created an account and joined your project on Crowdin to see how it work.

**Comment by abelrodriguez** [comment]
> Hello,
> 
> Thank you for the feature.
> 
> I just created an account and joined your project on Crowdin to see how it work.

@btiteux now you're administrator.

**Comment by btiteux** [comment]
Thank you.

**Comment by abelrodriguez** [comment]
Hello @veler 

sorry for my total absence these two months. My work had me absorbed.

Yes, I want to transfer the ownership of the project to you as I said previously but I can't transfer a project, I have to remove it and you create it (I should have read the Terms and Conditions first 😄).

But that's not a problem. I can transfer the knowledge about the project configuration to you and use my pull request to get the changes in the files.

Let me know when you will be available to delete the project and create it next.

Best regards!

**Comment by veler** [comment]
Hello,
Sorry for the late answer. Anytime works for me :)

**Comment by abelrodriguez** [comment]
I've already deleted the Crowdin project, **you should create it now**. 😉 

About the settings:
- When you set the branch configuration, you should set a filter like the following:
image
Source: `/src/dev/impl/DevToys/Strings/en-US/*.resw`
Translated: `/src/dev/impl/DevToys/Strings/%locale%/%original_file_name%`

Additionally, in `Language Mapping`, add the following mapping (to keep the same structure in DevToys repository):
image
Chinese Simplifed --> zh-Hans
Chinese Traditional --> zh-Hant

I think the rest of the configuration is sufficiently descriptive and needs no special mention. 😉

**Comment by veler** [comment]
Thank you so much @abelrodriguez !! :D I follow your guidance and now have a Crowdin project here:
https://crowdin.com/project/devtoys

I still need to update the `CONTRIBUTING.md` instructions for translation along with getting more familiar with the whole workflow and figure out how external people can contribute to it. But overall, it's great!

I will close this PR. But be sure that we (@btiteux  and I) are very thankful for making us discover this translation tooling and helping us setting it up! 😁

**Pull request closed without merging**
