### PR TITLE
Update Simplified Chinese translation

### PR DESCRIPTION
**Pull request by Nyerst**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

Chinese translation is outdated.

## What is the new behavior?

- [x] Translate new files
- [x] Improve the existing translation by
  - [x] Make "MenuDisplayName" follow the original expression
- [ ] Ready for review

## Quality check

Before creating this PR, have you:

- [x] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [ ] Verified that the change work in Release build configuration
- [ ] Checked all unit tests pass

### CODE REVIEW

**Comment by veler** [comment]
Hi,
Thanks you for this update. @Gaoyifei1011, would you like to take a look at it and tell us if it looks good to you, please?

**Comment by YuhanKun** [comment]
翻译看起来很棒啊，等了好久了还没更新中文有点难受
This looks prertty good.

**Review by YuhanKun — APPROVED** [review]
Looks good

**Comment by veler** [comment]
Thank you @YuhanKun for confirming :)

**Review by veler — APPROVED** [review]

**Pull request merged**
