### PR TITLE
Ported Text Escape/ Unescape tool

### PR DESCRIPTION
**Pull request by veler**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] New feature or enhancement
- [ ] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [X] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

DevToys 2.0 doesn't have a Text Escape / Unescape tool yet

Issue Number: #468

## What is the new behavior?

Ported the tool from DevToys 1.0 to 2.0. Issue #468 is solved through the fact that DevToys 2.0 has an option to select what end of line character should be used in Settings. Let's start with this for now. If unhappy, we could create an option specifically in this tool.

## Other information

image

## Quality check

Before creating this PR:

- [X] Did you follow the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
- [ ] Did you verify that the change work in Release build configuration
- [X] Did you verify that all unit tests pass
- [X] If necessary and if possible, did you verify your changes on:
   - [X] Windows
   - [ ] macOS (DevToys 2.0)
   - [ ] Linux (DevToys 2.0)

### CODE REVIEW

**Review by btiteux — APPROVED** [review]
I'm ok with the pull request but we need some Unit Tests on the GUI  :)

Before merging this pull request #971 , we have one to add support for Linux escape lines, too. Can we add the support at the same time?

**Comment by veler** [comment]
Hey @btiteux 

> Before merging this pull request #971 , we have one to add support for Linux escape lines, too. Can we add the support at the same time?

As I said in the PR description, issue #468 (which #971 solves in DevToys 1.0) is solved through the fact that DevToys 2.0 has an option to select what end of line character should be used in Settings. I'd suggest to limit ourselves to this for now and wait for more feedback. The reason of this push back is that the end of line sequence is set at the Monaco editor level. So replacing end of line in the string we hold in memory won't be efficient because Monaco will overwrite it constantly (when the user do any edit, or when copying or pasting into the editor).

A workaround is to add a new API to DevToys.API that would allow to customize the end of line sequence for a given `IUIMultiLineTextInput`. I'd like to try to avoid it (for now) in order to keep the API simple and don't give too much freedom (which translates into a risk of inconsistency between tools).

The setting I'm referring to above has already been tested on Linux.

image

Note that `\r (Mac)` is not supported by Monaco. Note also that `\r` on Mac is not supported after Mac OS 9, which DevToys doesn't target anyway.

**Comment by veler** [comment]
> we need some Unit Tests on the GUI :)

Done :-)

**Comment by btiteux** [comment]
We can go with the settings for the moment. But I think it's more user friendly to have a list here and that would avoid changing the settings for the whole apps.

**Comment by veler** [comment]
> We can go with the settings for the moment. But I think it's more user friendly to have a list here and that would avoid changing the settings for the whole apps.

I ultimately agree :-)

**Pull request merged**
