### PR TITLE
Update Japanese translation

### PR DESCRIPTION
**Pull request by ScratchBuild**
## Pull request type

Please check the type of change your PR introduces:

- [x] Internationalization and localization

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

- Update Japanese translation.

## Quality check

Before creating this PR, have you:

- [X] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [X] Verified that the change work in Release build configuration
- [X] Checked all unit tests pass

### CODE REVIEW

**Review by niyari — COMMENTED** [review]
For those of you who can't read Japanese, I've left it in English.

**Comment by btiteux** [comment]
Hello, @ScratchBuild  & @niyari are we keeping the changes? Or do you want to keep it in English?

**Comment by niyari** [comment]
@btiteux 
Please leave it in English for now.
The language settings are not updated immediately, so English text is needed for non-Japanese users to revert the settings.
Here we need both languages to be short and precise.

**Comment by btiteux** [comment]
Ok thank you @niyari.

I'm closing the pull request.

**Pull request closed without merging**
