### PR TITLE
Show current page title in TaskBar

### LINKED ISSUE #291: Show the currently selected category in the title bar
### What's the Problem?

If you have multiple DevToys running, it's inconvenient to find the window you want because the title bars are all the same
image1
.

### Solution/Idea

When multiple DevToys are running, for example, it is easier to select a target for window switching if the title bar displays something like "DevToys - Json Formatter".

### Alternatives

Just putting a sequential number at the end of the title bar in the order that DevToys was launched will improve things a bit.

### Priorities

_No response_

### DevToys Version

_No response_

### Comments

_No response_

### PR DESCRIPTION
**Pull request by veler**
## Pull request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] New feature or enhancement
- [X] UI change (please include screenshot!)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

Issue Number: Closes #291

## What is the new behavior?

We now display the group or tool title in the task bar.

## Other information

image

## Quality check

Before creating this PR:

- [X] Did you follow the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [X] Did you build the app and test your changes?
- [ ] Did you check for accessibility? On Windows, you can use Accessibility Insights for this.
- [ ] Did you verify that the change work in Release build configuration
- [ ] Did you verify that all unit tests pass
- [ ] If necessary and if possible, did you verify your changes on:
   - [X] Windows
   - [ ] macOS (DevToys 2.0)
   - [ ] Linux (DevToys 2.0)

### CODE REVIEW

**Comment by JaiganeshKumaran** [comment]
Better to use the standard format "page name - app name".

**Comment by veler** [comment]
> Better to use the standard format "page name - app name".

Good point! Will do this, thanks for the idea! :)

**Comment by veler** [comment]
Done
image

**Review by btiteux — APPROVED** [review]
Hello, it's good for me with the new title

**Pull request merged**
