### PR TITLE
Fixing checksum comparison issue (#396)

### PR DESCRIPTION
**Pull request by astegi-dev**
## Pull request type

Please check the type of change your PR introduces:

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

Currently, there is no visual indication of the comparison of outputs.

Issue Number: #396 

## What is the new behavior?

When the Output field and the Output Comparsion field both have value, then a text appears stating "The hashes are the same." or "The hashes are different.", whether the two fields have the same or different values.

## Quality check

Before creating this PR, have you:

- [X] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [X] Verified that the change work in Release build configuration
- [X] Checked all unit tests pass

### CODE REVIEW

**Review by veler — CHANGES_REQUESTED** [review]
Hello,
That's a simple, yet great addition! Thank you for this!

One thing I'd suggest though, the choice of color for the text doesn't work great in Light mode.

image

I'd suggest using an InfoBar, like in Number Base Converter.

image

See here: 
https://github.com/veler/DevToys/blob/5e423b37edee81af1e83f6a202d8073036658c8c/src/dev/impl/DevToys/Views/Tools/Converters/NumberBaseConverter/NumberBaseConverterToolPage.xaml#L31-L34

You can also use the `IsClosable` property of this control to hide the close button at the right (I think it would make sense to not being able to close this information).

Even better, you could make the info bar yellow or red when the hash isn't matching, and green (Severity = Success) when it matches. What do you think about it?

**Comment by astegi-dev** [comment]
Yeah, sure, I'm fixing that.

I am not an experienced UWP developer, I didn't know such control exists, but definitely makes more sense. :)

**Comment by astegi-dev** [comment]
Screenshots of the modification:
When hashes match:
image

When hashes does not match:
image

On light background:
image
image

**Review by veler — APPROVED** [review]
Hello,
Sorry for the late answer. It looks all good now :D Thank you so much for this contribution! Love it !

**Pull request merged**
