### PR TITLE
Keep original encoding in declaration

### PR DESCRIPTION
**Pull request by YSternlicht**
## Pull request type

Please check the type of change your PR introduces:

- [ x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Internationalization and localization
- [ ] Other (please describe):

## What is the current behavior?

https://github.com/veler/DevToys/issues/355

Issue Number: N/A

## What is the new behavior?

After having the xml as a string, we replace the hard coded utf-16 to whatever the user input, or removing it if it was omitted
-
-
-

## Quality check

Before creating this PR, have you:

- [ ] Followed the code style guideline as described in [CONTRIBUTING.md](https://github.com/veler/DevToys/blob/main/CONTRIBUTING.md)
- [ ] Verified that the change work in Release build configuration
- [ ] Checked all unit tests pass

### CODE REVIEW

**Comment by jwfxpr** [comment]
Grats on your first PR to the repository @YSternlicht! 😊👍

One suggestion/comment. Here, you check for an XmlDeclaration element:

https://github.com/veler/DevToys/blob/7abeeaf6e9c6100df90cd8f9b9353acb26460e26/src/dev/impl/DevToys/Helpers/XmlHelper.cs#L102

I'd try moving this code block up a few lines to be above the `stringBuilder` declaration, and use pattern matching like this:

```c#
                if (xmlDocument.FirstChild is XmlNodeType.XmlDeclaration declaration)
```

This way, instead of using `stringBuilder.Replace()`, you can simply directly set the value of the [`declaration.Encoding`](https://docs.microsoft.com/en-us/dotnet/api/system.xml.xmldeclaration.encoding?view=net-6.0) property before the XmlDocument is written out, rather than manipulating the output after the fact.

Setting `declaration.Encoding = string.Empty` might remove the element from the declaration, though the documentation does say:

>If an encoding attribute is not included, UTF-8 encoding is assumed when the document is written or saved out.

So that would need a bit of testing. It's not clear if that is literally just the output encoding, or if there would be a `encoding="utf-8"` element instead of no encoding element in the output.

Personally I think that setting `XmlDeclaration.Encoding` is probably more reliable than `Replace()`, since some future refactor might, e.g., change that default encoding somehow. You would end up accidentally replacing the first instance of `"utf-16"` somewhere else in the document. 😊

Also, here:

https://github.com/veler/DevToys/blob/7abeeaf6e9c6100df90cd8f9b9353acb26460e26/src/dev/impl/DevToys/Helpers/XmlHelper.cs#L104

You're scanning the xmlDocument _output_ for the encoding string, rather than the `input`. Is that intended? Either way, if you move the code above the declaration of `stringBuilder`, you'll have to change it over to scanning the `input`:

```c#
                    Match match = Regex.Match(string.Split('>', 2)[0], @"(?<=encoding\s*=\s*"")[^""]*", RegexOptions.None);
```

The `.Split('>', 2)[0]` will make sure that you only match the first element in the input, and don't accidentally match any random `encoding` element somewhere else in the input. There's probably a more elegant way to do that, that's off the top of my head. 😊

**Comment by YSternlicht** [comment]
Thanks @jwfxpr for your comment.

I agree with you that replacing the string after it has been placed in the string builder is not ideal. 
However, a couple of issues forced me to do this.

There are 2 possible encodings to set, one on the xmlWriterSettings, and one on the xmlWriter . Settings property.

https://github.com/YSternlicht/DevToys/blob/7abeeaf6e9c6100df90cd8f9b9353acb26460e26/src/dev/impl/DevToys/Helpers/XmlHelper.cs#L68

https://github.com/YSternlicht/DevToys/blob/7abeeaf6e9c6100df90cd8f9b9353acb26460e26/src/dev/impl/DevToys/Helpers/XmlHelper.cs#L97

**Comment by jwfxpr** [comment]
> I agree with you that replacing the string after it has been placed in the string builder is not ideal. However, a couple of issues forced me to do this.
> ...

Seems like you've already investigated the situation. 😊 I didn't have the opportunity to play with the `XmlDocument` or `XmlWriterSettings` classes before writing the comment, and I think you've covered the same things I would have and I'd have come to the same conclusion as you. 👍

> A possible solution could be to remove the StringBuilder and use a memory stream instead and return that. This will then default to utf-8. That could get very problematic as we will have to specify the encoding before we convert that stream into a string.

Yeah, I agree with you, changing the default to a different default with a more complex process isn't a great solution.

As far as I can see, if we're using `System.Xml` `XmlDocument` and `XmlWriter` to achieve the formatting, this is probably the best workaround available.

@veler, should a couple of simple test cases for this be added to `src/tests/DevToys.Tests/Helpers/XmlHelperTests.cs` in this PR?

**Comment by veler** [comment]
Hi all,

Thank you very much @YSternlicht for opening this PR and proposing this change. 

> As far as I can see, if we're using System.Xml XmlDocument and XmlWriter to achieve the formatting, this is probably the best workaround available.

I agree with this. It seems to be the best workaround so far.

> should a couple of simple test cases for this be added to src/tests/DevToys.Tests/Helpers/XmlHelperTests.cs in this PR?

Definitely! @YSternlicht , would you please be able to add some unit tests? :)

**Comment by YSternlicht** [comment]
Hi @veler 

Sure thing. 

Been a busy week but will try get the tests written over the weekend.

**Comment by veler** [comment]
> Hi @veler 
> 
> Sure thing. 
> 
> Been a busy week but will try get the tests written over the weekend. 

No worries, there's no hurry 😊
Thank you very much!

**Comment by YSternlicht** [comment]
OK.

Tests written.

**Review by veler — APPROVED** [review]
Awesome! It looks great! Thank you for this fix! :)

**Pull request merged**
